services:
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
    
  back-end:
    build:
      context: ./back-end
    container_name: back-end
    ports:
      - "4000:4000"