# name: VTMP CI/CD Pipeline Demo
# on:
#   we want to run the ci only when it's a PR

# jobs:
#   job-1: (for front-end)
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: working directory we want to run
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: which node version we want to use

#       - name: Install dependencies
#         run: what is the command to install dependencies
      
#       - name: Run lint
#         run: what is the command to run lint

#       - name: Run tests
#         run: what is the command to run tests
